### PR TITLE
Added Nvidia Issues

### PR DESCRIPTION
**Pull request by eastcoastcoder**

### CODE REVIEW

**Comment by ArtSabintsev** [comment]
Can you elaborate on your last comment here: https://github.com/ArtSabintsev/Ethminer-for-macOS/issues/15#issuecomment-357561380?

It is never a good idea to default to an older version of Xcode and Xcode Command Line Tools, especially one that is 2.5 years old.

**Comment by eastcoastcoder** [comment]
Normally I'd agree. For some reason it won't compile even with Xcode 8's CLT. As it throws error another
`The version ('80000') of the host compiler ('Apple clang') is not supported`
I guess this is due to an outdated CUDA toolkit, not really sure but it's nvcc related.

After I used 7.3 I was able to compile, then I noticed the --cuda-devices argument wouldn't work. So I had to add `-DETHASHCUDA=ON` as another cmake arugment....which threw another unrelated error, but somehow I didn't receive the error today and it compiled successfully. 

I can run both my AMD and Nvidia cards with the following args (putting this here if anyone else is curious)
`./ethminer --farm-recheck 200 -X -S us2.ethermine.org:4444 -FS us2.ethermine.org:14444 -O <WALLET>.<WORKER> --cuda-devices 2 --opencl-device 1`

**Comment by ArtSabintsev** [comment]
Have you tried Xcode 9.2?

**Comment by eastcoastcoder** [comment]
Oh yes, sorry I forgot to mention that. When compiling with the Nvidia arguments on 9.2 it gives an nvcc error about clang version ‘90000’ being unsupported. Unless I’m missing something, it seems like the only success I’ve had was with 7.3 which is a real bummer, but it works.

**Comment by ArtSabintsev** [comment]
Hmm, it seems that whatever is depending on Clang is really outdated.

**Comment by ArtSabintsev** [comment]
And you're 100% sure you're running CUDA 9.0?

Can you check with ` /usr/bin/cc --version`?

Here's what I get:

```bash
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by eastcoastcoder** [comment]
Yep, retested from a fresh clone today. Here's a screen cap of the output.

https://webmshare.com/3XVeq (clang version output)
https://webmshare.com/JnDPJ (Fixing compute_20)
https://webmshare.com/OXabB (Actual clang 9000 error)

From here I'd downgrade Xcode tools, run the make commands again, and it would work.
I have a precompiled binary with CUDA fully enabled if you'd be willing to host it in the releases section. It looks like anyone who wants the CUDA support has to build from source.

**Comment by ArtSabintsev** [comment]
Those videos don't work, but no matter.

Do me a favor and leave the existing Nvidia Installation as is, however, add your comments as an option under the Nvidia part (instead of replacing it)

The Issues section can remain. I'll make slight augmentations later after I merge.

**Comment by ArtSabintsev** [comment]
Has a change of hear. Merging as is. Thanks!

**Pull request merged**
